#!/bin/bash

set -o errexit
set -o noglob
set -o nounset
set -o pipefail

################################################################################
# LICENSE
#
# This software is released under the Revised BSD License.
# 
# Copyright (c) 2015, Ryan Chapin, http:www.ryanchapin.com         
# All rights reserved.                     
#                                                                     
# Redistribution  and  use  in  source  and binary forms, with or
# without modification, are permitted provided that the following
# conditions are met:
#                                                                     
# *   Redistributions  of  source  code  must  retain  the  above
# copyright  notice,  this  list  of conditions and the following
# disclaimer.
# 
# *  Redistributions  in  binary  form  must  reproduce the above
# copyright  notice,  this  list  of conditions and the following
# disclaimer  in the documentation andor other materials provided
# with the distribution.
# 
# *  Neither  the  name  of  Ryan  Chapin  nor  the  names of its
# contributors may be used to endorse or promote products derived
# from this software without specific prior written permission.
#                                                                     
# THIS   SOFTWARE  IS  PROVIDED  BY  THE  COPYRIGHT  HOLDERS  AND
# CONTRIBUTORS  "AS  IS"  AND  ANY EXPRESS OR IMPLIED WARRANTIES,
# INCLUDING,  BUT  NOT  LIMITED  TO,  THE  IMPLIED  WARRANTIES OF
# MERCHANTABILITY  AND  FITNESS  FOR  A  PARTICULAR  PURPOSE  ARE
# DISCLAIMED.   IN   NO  EVENT  SHALL  RYAN  CHAPIN,  ANY  HEIRS,
# SUCCESSORS,  EXECUTORS AND OR ASSIGNS BE LIABLE FOR ANY DIRECT,
# INDIRECT,  INCIDENTAL,  SPECIAL,  EXEMPLARY,  OR  CONSEQUENTIAL
# DAMAGES   (INCLUDING,   BUT  NOT  LIMITED  TO,  PROCUREMENT  OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
# BUSINESS  INTERRUPTION)  HOWEVER  CAUSED  AND  ON ANY THEORY OF
# LIABILITY,  WHETHER  IN  CONTRACT,  STRICT  LIABILITY,  OR TORT
# (INCLUDING  NEGLIGENCE  OR OTHERWISE) ARISING IN ANY WAY OUT OF
# THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#
################################################################################
#
# Script for starting and stopping hadoop services in the Cloudera Hadoop
# distribution for pseudo-distributed mode.
#
# name:     hadoop-services
# author:   Ryan Chapin <http://www.ryanchapin.com/contact.html>
# created:  2013-03-25
# modified: 2015-10-21
# 
################################################################################
# EXIT CODES:
#
# 1 : Invalid -c command argument 
# 2 : Invalid -d command argument
# 3 : init script execution failed
#
################################################################################
# USAGE:

function about {
  cat << EOF
$ME - start|stop|status for hadoop service daemons, grouped  by  the
                  type of service in a Cloudera pseudo-distributed installation.
                  Must be run as root.  Currently supports  CDH 4 and above.

                  Services supported: hdfs-services,  mapreduce  services  (MRv1
                  and MRv2)
EOF
}

function usage {
  cat << EOF
Usage: $ME [OPTIONS] -d [daemon-group] -c [init-command]

  -d daemon-group [hdfs|mr]

  -c init script command to execute [start|stop|status]

Options:
  -h HELP
    Outputs this basic usage information.

  -s SILENT
    Silence all STDOUT from each init script

  --more-help EXTENDED HELP
    Extended help and documentation.
EOF
}

function extended_usage {
cat << EOF
Extended Usage:

  This script will execute the command argument for each of the following
  hadoop service init scripts:

  hdfs:
  ${HDFS_INIT_SCRIPTS[*]}

  mapreduce:
  ${MR_INIT_SCRIPTS[*]}

Example:

  # $ME -d hdfs -c start
  Will start all of the hdfs-service daemons.

  # $ME -d mr -c stop -s
  Will stop all of the mapreduce daemons surpressing and STDOUT or STDERR
EOF
}

################################################################################

source $(which hadoop-utility-functions)

################################################################################
# CONFIGURATIONS:

ME="$(basename $0)"

#
# location of init.d directory
#
INITD_PATH=/etc/init.d

#
# array of hdfs init scripts/services to invoke
#
declare -a HDFS_INIT_SCRIPTS=( hadoop-hdfs-namenode \
      hadoop-hdfs-secondarynamenode\ 
      hadoop-hdfs-datanode )

#
# pull in the version of MR that we are running along with the array of
# mapreduce init scripts
#
source $(which mr-version)

################################################################################
#
# Here we define variables to store the input from the command line arguments as
# well as define the default values.
#
HELP=0
SILENT=0
MORE_HELP=0
DAEMON_GROUP=""
CMD_ARG=""

PARSED_OPTIONS=`getopt -o hsc:d: -l more-help -- "$@"`

# Check to see if the getopts command failed
if [ $? -ne 0 ];
then
  echo "Failed to parse arguments"
  exit 1
fi

eval set -- "$PARSED_OPTIONS"

# Loop through all of the options with a case statement
while true; do
  case "$1" in
    -h)
      HELP=1
      shift
      ;;

    -s)
      SILENT=1
      shift
      ;;

    -d)
      DAEMON_GROUP=$2
      shift 2
      ;;

    -c)
      CMD_ARG=$2
      shift 2
      ;;

    --more-help)
      MORE_HELP=1
      shift
      ;;

    --)
      shift
      break
      ;;
  esac
done

if [ "$MORE_HELP" -eq 1 ];
then
  about
  echo ""
  usage
  echo ""
  extended_usage
  exit
fi

if [ "$HELP" -eq 1 ];
then
  usage
  exit
fi

###############################################################################

case "$CMD_ARG" in
  start)
    ;;
  stop)
    ;;
  status)
    ;;
  *)
    output_msg "invalid command option [$CMD_ARG] provided"
    output_msg "$(usage)"
    output_msg "exiting...."
    exit 1
    ;;
esac

#
# 'Point' the array that we will loop through to the correct set of init
# scripts based on the -d arg
#
case "$DAEMON_GROUP" in
  hdfs)
    declare -a INIT_SCRIPTS=(${HDFS_INIT_SCRIPTS[*]})
    ;;
  mr)
    declare -a INIT_SCRIPTS=(${MR_INIT_SCRIPTS[*]})
    ;;
  *)
    output_msg "invalid daemon-group option [$DAEMON_GROUP] provided"
    output_msg "$(usage)"
    output_msg "exiting...."
    exit 2
    ;;
esac

output_msg "executing the [${CMD_ARG}] command for [${DAEMON_GROUP}] daemons"

#
# Turn off errexit so that we can simply report a failure of one of the
# commands instead of it forcing an exit.
#
set +o errexit

#
# loop through the INIT_SCRIPTS and invoke the CMD_ARG on each of
# the services
#
for i in "${INIT_SCRIPTS[@]}"
do
  CMD="service $i ${CMD_ARG}"

  if [ "$SILENT" -eq 1 ]
  then
    CMD="$CMD > /dev/null 2>&1"
  fi

  # echo "$CMD"
  eval $CMD

  RETVAL="$?"

  if [ "$RETVAL" -ne "0" ] && [ "$CMD_ARG" != "status" ]
  then
    output_msg "init script execution failed with return code $RETVAL"
    output_msg "exiting..."
    exit 3 
  fi
done

